# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - 'releases/**'
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Extract branch name
      run: |
        echo "On branch ${GITHUB_REF#refs/heads/releases/}"
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/releases/})"
      id: extract_branch      
    - name: Echo name
      run: | 
        echo "${{steps.extract_branch.outputs.branch}}"
